<?xml version="1.0"?>
<package format="3">
  <name>handsfree_rtk</name>
  <version>0.1.0</version>
  <description>ROS 2 driver for HandsFree RTK UM98x receivers.</description>
  <maintainer email="handsfree@todo.todo">handsfree</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-serial</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
